# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog
description: Veritas Lux Mea
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ritaru.github.io # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Rita Amane
  email: uuil31@gmail.com

disqus_shortname: rita
copyright: "&copy; All rights reserved. by Rita"

paginate: 5
paginate_path: "/page-:num/"

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
remote-theme: qwtel/hydejack
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
