# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog
email: uuil31@gmail.com
description: "Veritas Lux Mea"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ritaru.github.com # the base hostname & protocol for your site, e.g. http://example.com
github_username: ritaru

#theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack

accent_color: rgb(215,91,143)
theme_color: rgb(215,91,143)

disqus_shortname: rita

author:
  name: Rita Amane
  email: uuil31@gmail.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - README.md
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
